sudo: required
service:
  - docker

before_install:
  - docker build -t horatiuandrei/udemy-docker-kubernetes-react -f Dockerfile.dev .

script:
  - docker run -e CI=true horatiuandrei/udemy-docker-kubernetes-react npm run test