name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker Login (Action)
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - run: docker build -t horatiuandrei/udemy-docker-kubernetes-react -f Dockerfile.dev .
      - run: docker run -e CI=true  horatiuandrei/udemy-docker-kubernetes-react npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: udemy-docker-kubernetes-react
          environment_name: Udemy-docker-kubernetes-react-env
          existing_bucket_name: elasticbeanstalk-ap-southeast-1-208838686419
          region: ap-southeast-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip